# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2193990c0b5044a7bfa91c6443a78b0abe5a85e2f0438d53353f9acef19b20e934d5c5a96fa6081c53cdeb9729b86a6482182932db3f512e35bf149a07e6786

test:
  secret_key_base: 265d1e47a701842718c4362cdbebe11e57d758bd3442f5f0dd89bee0397a1d5c7d6cf63a5818858775ada48cb2768a8c1f2c143b02cf8dcf74d8e8b57b3a9ee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
